application: aep-sample
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /favicon.ico/?
  static_files: _generated_media/1/img/favicon.ico
  upload: _generated_media/1/img/favicon.ico
  
- url: /test.*
  script: gaeunit.py
  
- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py
