application: cametrics-stress
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /favicon.ico/?
  static_files: _generated_media/1/img/favicon.ico
  mime_type: image/gif 
  upload: _generated_media/1/img/favicon.ico
  
- url: /test.*
  script: gaeunit.py
  
- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (test/.*)|
 (docs/.*)|
 (clients/.*)|
 (.*\.md)|
 (license\.txt)|
 (setup.py)
 )$